name: Check HTTPS Certificate Expiry

on:
  workflow_dispatch:
    inputs:
        url:
            type: string
            required: true
            description: 'URL for checking SSL Certificate'

jobs:
    checkSSL:
        runs-on: ubuntu-latest
        steps:
            - name: Check OpenSSL version
              run: openssl version

            - name: Check SSL expiry date
              run: |
                expiryDate=$(echo | openssl s_client -servername ${{ inputs.url }} -connect ${{ inputs.url }}:443 2>/dev/null | openssl x509 -noout -dates | grep 'notAfter')
                expiryDate=$(echo $expiryDate | awk -F= '{print $2}')
                domainName=${{ inputs.url }}
                echo "### Workflow variables" >> $GITHUB_STEP_SUMMARY
                echo "| Domain Name   | SSL Expiry Date  |" >> $GITHUB_STEP_SUMMARY
                echo "| ---------- | ----------- |" >> $GITHUB_STEP_SUMMARY
                echo "| $domainName  | $expiryDate  |" >> $GITHUB_STEP_SUMMARY
                
            